name: Dollar-Yen Rate Check

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごとに実行

jobs:
  check_rate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance requests
    - name: Run rate check script
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        TARGET_RATE: ${{ secrets.TARGET_RATE }}
        NOTIFICATION_INTERVAL: ${{ secrets.NOTIFICATION_INTERVAL }}
      run: python finance_dollyen.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add last_notification.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update last notification time" && git push)
